baseURL = "https://lunainternet.com"
disqusShortname = ""
googleAnalytics = ""
paginate = "3"
summaryLength = "15"
theme = "bigspring"
title = "Luna Internet"
[markup.goldmark.renderer]
unsafe = true
